#################################
# 语言配置，这里我不是用来配置语言 #
#################################

[en]
languageName = "English"
weight = 1
# languagedirection = 'rtl'

[en.Params]
CanonicalLinkText = 'Originally published at'

# 英文单独设置profileMode
[en.Params.profileMode]
enabled = true
title = "00000000!!!"
# subtitle = "😀😃😄😁😆😅🤣😂🙂🙃😉😊😇🥰😍🤩😘😗😚😙😋😛😜🤪😝🤑🤗🤭🤫🤔🤐🤨😐😑😶😶‍🌫️😏😒🙄😬😮‍💨🤥😌😔😪🤤😴😷🤒🤕🤢🤮🤧🥵🥶🥴😵😵‍💫🤯🤠🥳😎🤓🧐😕😟🙁☹️😮😯😲😳🥺😦😧😨😰😥😢😭😱😖😣😞😓😩😫🥱😤😡😠🤬😈👿💀☠️💩🤡👹👺👻👽👾🤖😺😸😹😻😼😽🙀😿😾"
# imageUrl = "/images/site/icon192.png"
# imageTitle = "Linlccc"
# imageWidth = 120
# imageHeight = 120

[[en.Params.profileMode.buttons]]
name = 'Search'
url = 'search'

[[en.Params.profileMode.buttons]]
name = 'Posts'
url = 'posts'

[[en.Params.profileMode.buttons]]
name = 'Tags'
url = 'tags'

[[en.Params.profileMode.buttons]]
name = 'Archives'
url = 'archives'


[zh]
languageName = "中文"
weight = 1
# 语言方向
# languagedirection = 'rtl'
