##############################################################################
# 页面访问链接配置                                                            #
# https://gohugo.io/content-management/urls/#permalink-configuration-values #
#############################################################################

posts = '/posts/:slugorfilename/'
