# 基本配置

# 默认语言
defaultContentLanguage: zh
# 默认语言是否在子目录中
defaultContentLanguageInSubdir: false
# 是否检测内容中的 中/日/韩 文，使 .Summary .WordCount 正确运行
hasCJKLanguage: true
# 启动Emoji表情支持
enableEmoji: true
# 设置时区 亚洲/重庆 see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Chongqing
# 网站声明
copyright:
# 禁用 Hugo 注入生成器元标记
disableHugoGeneratorInject: false
# 启用 robots.txt （标准网络协议，用于告知网络爬虫哪些页面可以被爬取，哪些页面不能被爬取）
enableRobotsTXT: true
# 如果站点由 git 管理，将页面的 Lastmod 参数设置为最后 git 提交日期
enableGitInfo: true

# 每页文章数量
paginate: 5
# 文章摘要长度
summaryLength: 100
