#################################
# 语言配置，这里我不是用来配置语言 #
#################################

en:
  languageName: English
  weight: 1
  # languagedirection: rtl

  Params:
    CanonicalLinkText: Originally published at

    # 英文单独设置profileMode
    profileMode:
      enabled: true
      title: 00000000!!!
      # subtitle: 😀😃😄😁😆😅🤣😂🙂🙃😉😊😇🥰😍🤩😘😗😚😙😋😛😜🤪😝🤑🤗🤭🤫🤔🤐🤨😐😑😶😶‍🌫️😏😒🙄😬😮‍💨🤥😌😔😪🤤😴😷🤒🤕🤢🤮🤧🥵🥶🥴😵😵‍💫🤯🤠🥳😎🤓🧐😕😟🙁☹️😮😯😲😳🥺😦😧😨😰😥😢😭😱😖😣😞😓😩😫🥱😤😡😠🤬😈👿💀☠️💩🤡👹👺👻👽👾🤖😺😸😹😻😼😽🙀😿😾
      # imageUrl: /images/site/icon192.png
      # imageTitle: Linlccc
      # imageWidth: 120
      # imageHeight: 120
      buttons:
        - name: Search
          url: search
        - name: Posts
          url: posts
        - name: Tags
          url: tags
        - name: Archives
          url: archives

zh:
  languageName: 中文
  weight: 1
  # 语言方向
  # languagedirection: rtl
