# 中文菜单配置

main:
  # 标识符
  - identifier: search
    # 名称
    name: 搜索
    # 链接
    url: /search/
    # 权重
    weight: 10
    # 在name前添加内容（允许html）
    pre:
    # 在name后添加内容（允许html）
    post:
    # 鼠标悬停显示文本
    title:

  - identifier: posts
    name: 文章
    url: /posts/
    weight: 20

  - identifier: tags
    name: 标签
    url: /tags/
    weight: 30

  - identifier: categories
    name: 分类
    url: /categories/
    weight: 40

  - identifier: archives
    name: 档案
    url: /archives/
    weight: 50
