###########
# 中文菜单配置 #
###########

main:
  - # 标识符
    identifier: posts
    # 名称
    name: 文章
    # 链接
    url: /posts/
    # 权重
    weight: 3
    # 在name前添加内容（允许html）
    pre:
    # 在name后添加内容（允许html）
    post:
    # 鼠标悬停显示文本
    title:

  - identifier: search
    name: 搜索
    url: /search/
    weight: 1

  - identifier: tags
    name: 标签
    url: /tags/
    weight: 5

  - identifier: archives
    name: 档案
    url: /archives/
    weight: 7

  # - identifier: linlccc
  #   name: Linlccc
  #   url: https://linlccc.github.io/
  #   weight: 9

  # - identifier: categories
  #   name: 分类
  #   url: /categories/
  #   weight: 10
