###########
# 菜单配置 #
###########

[[main]]
  # 标识符
  identifier = 'posts'
  # 名称
  name = '文章'
  # 链接
  url = '/posts/'
  # 权重
  weight = 1
  # 在name前添加内容（允许html）
  pre = ""
  # 在name后添加内容（允许html）
  post = ""
  # 鼠标悬停显示文本
  title = ''

[[main]]
  identifier = 'tags'
  name = '标签'
  url = '/tags/'
  weight = 2
