####################################################
# 使用 hugo --environment development 指令构建测试版 #
####################################################
baseURL = 'http://127.0.0.1:5500/'
title = "开发"

# 构建草稿
buildDrafts = true
# 构建过期
buildExpired = true
# 构建未来
buildFuture = true


# googleAnalytics = 'G-TQ3ZXPKKNM'
