####################################################
# 使用 hugo --environment development 指令构建测试版 #
####################################################
# 调试时要在其他设备上访问运行 hugo server --baseURL=http://192.168.31.188:1313/ --bind=0.0.0.0 --port=1313

baseURL: http://192.168.31.188:1313/
title: 开发

# 构建草稿
buildDrafts: true
# 构建过期
buildExpired: true
# 构建未来
buildFuture: true
